### ISSUE TITLE
Converting From Core PHP to MVC Framework 

### ISSUE THREAD

**Issue by dksami** [dksami/Accounting-System#1]
Plan it to Modify it and convert this app so that we can use it on MVC framework.

**Comment by PMessinezis** [comment]
Sami hi. I have free time and experience with Laravel/Vue. If you are interested I could help converting this project to a laravel app. Let me know.

**Comment by dksami** [comment]
@PMessinezis I really don't have time I want you to contribute in the conversion fully, I am being full time employed in 2 places, remotely and one on-site so I have time to work on. However, if you like to contribute you are welcome.

**Comment by PMessinezis** [comment]
No problem. It looks like a fun exercise. 

I have forked the repo and created a branch  named [laravel](https://github.com/PMessinezis/Accounting-System/tree/laravel). 

I have also moved all existing files (refered to as **core**) under laravel directory structure (`app/core` and `public/core`) and defined laravel routing to serve them under the route `/core` and it works fine.

If/when you have time you can take a look at [LARAVEL_ROADMAP](https://github.com/PMessinezis/Accounting-System/blob/laravel/LARAVEL_ROADMAP.md) and share your thoughts.

**Comment by dksami** [comment]
@PMEssinezis, send an email to me.
I will be watch and learning laravel wile would will be making changes. I will be there.

**Comment by PMessinezis** [comment]
Great - If at any point you want to have an online chat to go over any part of the code please let me know.

**Comment by PMessinezis** [comment]
@dksami you could watch [laravel branch](https://github.com/PMessinezis/Accounting-System/tree/laravel) of my fork. I will add a section on README on how to run it after cloning, now that it is a laravel project. The key steps, from the path where it is cloned at,  are :
-  run `composer install`
-  copy `.env.example` to `.env` (if not done already by composer)
-  inside `.env` update mysql connection parameters for `DB_CONNECTION` and `DB_CORE_xxx` sections (use a different database for the laravel part, e.g. accountNew)
-  run `php artisan migrate:fresh --seed`  (this will create the tables in accountNew and populate them)
-  run `npm install`
-  run `npm run dev` 
-  run `php artisan serve` (this will serve the project, usually at http://127.0.0.1:8000)
-  visit the local site
-  sign-on with username :  `me`   and password: `password`

location  `/`  serves the laravel version, while locations starting with `/core` serve the PHP core version.

Give it a try and let me know what you think.

**Comment by dksami** [comment]
@PMessinezis yes sfsg, reusing the same theme, make sure to do one thing, There is a problem with bottom modules that they don't enter data over a specific id of the user. Keep that in mind.

**Comment by dksami** [comment]
@PMessinezis thanks for your such contribution.
